version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      - POSTGRES_DB=gestao_vagas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

