name: Gestao de Vagas Application

on:
  push:
    branches: [master]

jobs:   
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        run: mvn clean install

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gestao_vagas .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gestao_vagas
